services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: clever-search-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cleaver_search_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - clever-search-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cleaver_search_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache & Queue
  redis:
    image: redis:7-alpine
    container_name: clever-search-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - clever-search-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: clever-search-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/cleaver_search_dev
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your-jwt
      CLERK_SECRET_KEY: sk_test_j9z0Dda9JfUE7UVXN3D6spZl7dzWulNFIQfPMyFLGx
      JWT_EXPIRES_IN: 7d
      CORS_ORIGIN: http://localhost:3000
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
      FORCE_COLOR: 1
    ports:
      - "3001:3001"
      - "4983:4983"
    volumes:
      - ./backend:/app:cached
      - /app/node_modules
      - ./shared:/app/shared:cached
    networks:
      - clever-search-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: npm run dev

  # Frontend Next.js App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: clever-search-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001/api/v1
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3001/api/v1
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_bmV3LWNhaW1hbi02MS5jbGVyay5hY2NvdW50cy5kZXYk
      CLERK_SECRET_KEY: sk_test_j9z0Dda9JfUE7UVXN3D6spZl7dzWulNFIQfPMyFLGx
      WATCHPACK_POLLING: true
      CHOKIDAR_USEPOLLING: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
      - /app/.next
      - ./shared:/app/shared:cached
    networks:
      - clever-search-network
    depends_on:
      - backend
    command: npm run dev



  # Redis Commander for Redis Management (Optional)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: clever-search-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - clever-search-network
    depends_on:
      - redis
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  clever-search-network:
    driver: bridge
