-- Skip adding name column as it already exists
-- ALTER TABLE "users" ADD COLUMN "name" varchar(255);--> statement-breakpoint
-- Skip adding preferences column as it already exists
-- ALTER TABLE "users" ADD COLUMN "preferences" jsonb DEFAULT '{}'::jsonb;