import { notFound } from 'next/navigation';
import BlogPostClient from '../BlogPostClient';
import { Metadata } from 'next';
import { generateBlogMetadata } from '@/lib/metadata';

// Function to generate metadata for blog posts
export async function generateMetadata({ params }: { params: { slug: string } }): Promise<Metadata> {
  const { slug } = await params;
  return generateBlogMetadata(slug);
}

export default async function BlogPost({ params }: { params: { slug: string } }) {
  const { slug } = await params;
  let PostComponent, meta;
  try {
    const mod = await import(`@/content/blog/${slug}.mdx`);
    PostComponent = mod.default;
    meta = mod.meta || {};
  } catch {
    return notFound();
  }

  // Example: relatedPosts could be generated by reading other MDX files, here static for now
  const relatedPosts = [];

  return (
    <BlogPostClient meta={meta} relatedPosts={relatedPosts}>
      <PostComponent />
    </BlogPostClient>
  );
} 