version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_prod
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis_prod
    volumes:
      - redis-data:/data
    restart: unless-stopped

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.prod
    container_name: backend_prod
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./prod.env
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data: 